# Required
version: 0.1.4

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
    builder: html
    configuration: source/conf.py
    fail_on_warning: false


