# Required
version: 0.1.4

# Set the version of Python and other tools you might need
build:
  os: windows-10
  tools:
    python: "3.9"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"

sphinx:
    builder: html
    configuration: source/conf.py
    fail_on_warning: false
